services:
  redis:
    image: redis
    restart: unless-stopped
    networks:
      - autograph-network
      
  mongodb:
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - mongodbdata:/data/db
    restart: unless-stopped
    networks:
      - autograph-network
      
  celery:
    build: .
    init: true # fix zombie processes
    command: xvfb-run celery -A tasks worker -l INFO --concurrency=5
    depends_on:
      - mongodb
      - redis
    mem_limit: 12g
    restart: unless-stopped
    volumes:
      - ./:/opt/autograph:ro
    deploy:
      mode: replicated
      replicas: 2
    user: 1000:1000
    networks:
      - autograph-network
    environment:
      - PYTHONUNBUFFERED=1
         
  backend:
    build: .
    env_file:
      - .env
    command: gunicorn app:app --bind 0.0.0.0:9876 --workers=8 --log-level=info --timeout 300 --access-logfile '-' --reload
    mem_limit: 8g
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./:/opt/autograph:ro
    depends_on:
      - mongodb
      - redis
      - celery
    networks:
      - autograph-network
    environment:
      - PYTHONUNBUFFERED=1


  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    expose:
      - 5555
    restart: unless-stopped
    depends_on:
      - redis
      - celery
    networks:
      - autograph-network


  nginx:
    build:
      context: ./proxy
      args:
          - FRONTEND_USERNAME=${FRONTEND_USERNAME}
          - FRONTEND_PASSWORD=${FRONTEND_PASSWORD}
          - BASEDOMAIN=${BASEDOMAIN}
          - CROSSORIGINDOMAIN=${CROSSORIGINDOMAIN}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    depends_on:
      - backend
    networks:
      autograph-network:
        # set aliases to the needed domains, so that the celery workers find them witouth external dns. This way, traffix stays on-host.
        aliases:
          - ${BASEDOMAIN}
          - ${CROSSORIGINDOMAIN}

      
##################################################################################################################
##### Volumes & Networks
##################################################################################################################



volumes:
  mongodbdata:

networks:
  autograph-network:
    driver: bridge
    enable_ipv6: false
    internal: false # allow outgoing internet access
    ipam:
      driver: default
      config:
        - subnet: 10.173.0.0/16
          gateway: 10.173.202.1
